#define GCC_VERSION (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)
#define GCC_TEST (GCC_VERSION > 0 && (GCC_VERSION < 40200 || GCC_VERSION > 40700))
#define INTEL_TEST (__INTEL_COMPILER >= 1300)
#define NULL_VAR (GCC_TEST || INTEL_TEST)
