communication/broadcast_boundary.o : data_structure.mod
communication/broadcast_elements.o : data_structure.mod
communication/broadcast_nodes.o : data_structure.mod
communication/broadcast_phys.o : phys_module.mod
communication/distribute_harmonics.o : parameters.mod
communication/distribute_harmonics.o : global_distributed_matrix.mod
communication/distribute_harmonics.o : mumps_module.mod
communication/distribute_nodes_elements.o : data_structure.mod
communication/distribute_vector.o : parameters.mod
communication/distribute_vector.o : global_distributed_matrix.mod
communication/distribute_vector.o : mumps_module.mod
communication/export_boundary.o : data_structure.mod
communication/export_grid.o : parameters.mod
communication/export_grid.o : data_structure.mod
communication/export_helena.o : data_structure.mod
communication/export_helena.o : phys_module.mod
communication/export_helena.o : data_structure.mod
communication/export_pov.o : parameters.mod
communication/export_pov.o : data_structure.mod
communication/export_pov.o : basis_at_gaussian.mod
communication/export_restart.o : data_structure.mod
communication/export_restart.o : phys_module.mod
communication/import_restart.o : data_structure.mod
communication/import_restart.o : phys_module.mod
communication/split_broadcast.o : mumps_module.mod
communication/update_deltas.o : data_structure.mod
communication/update_deltas.o : global_distributed_matrix.mod
communication/update_values.o : data_structure.mod
communication/vertex_is_local.o : murge_module.mod
datatypes/mod_data_structure.o : parameters.mod
data_structure.mod : datatypes/mod_data_structure.o
diagnostics/boundary_check.o : data_structure.mod
diagnostics/boundary_check.o : phys_module.mod
diagnostics/boundary_check.o : vacuum_response_module.mod
diagnostics/boundary_check.o : nodes_elements.mod
diagnostics/dlength.o : parameters.mod
diagnostics/energy.o : data_structure.mod
diagnostics/energy.o : gauss.mod
diagnostics/energy.o : basis_at_gaussian.mod
diagnostics/energy.o : phys_module.mod
diagnostics/find_axis.o : data_structure.mod
diagnostics/find_axis.o : gauss.mod
diagnostics/find_axis.o : basis_at_gaussian.mod
diagnostics/find_axis.o : data_structure.mod
diagnostics/find_flux_surfaces.o : data_structure.mod
diagnostics/find_xpoint.o : data_structure.mod
diagnostics/find_xpoint.o : gauss.mod
diagnostics/find_xpoint.o : basis_at_gaussian.mod
diagnostics/flux_surface_add_line.o : data_structure.mod
diagnostics/flux_surface_add_point.o : data_structure.mod
diagnostics/integrals_3D.o : data_structure.mod
diagnostics/integrals_3D.o : gauss.mod
diagnostics/integrals_3D.o : basis_at_gaussian.mod
diagnostics/integrals_3D.o : phys_module.mod
diagnostics/integrals.o : data_structure.mod
diagnostics/integrals.o : gauss.mod
diagnostics/integrals.o : basis_at_gaussian.mod
diagnostics/integrals.o : phys_module.mod
diagnostics/print_grid.o : data_structure.mod
diagnostics/psi_minmax.o : data_structure.mod
diagnostics/q_profile.o : data_structure.mod
diagnostics/q_profile.o : phys_module.mod
diagnostics/RZ_minmax.o : data_structure.mod
elements/initialise_basis.o : gauss.mod
elements/initialise_basis.o : basis_at_gaussian.mod
elements/initialise_basis.o : phys_module.mod
elements/interp.o : data_structure.mod
elements/interp_RZ.o : data_structure.mod
elements/mod_basis_at_gaussian.o : parameters.mod
elements/mod_basis_at_gaussian.o : gauss.mod
basis_at_gaussian.mod : elements/mod_basis_at_gaussian.o
gauss.mod : elements/mod_gauss.o
grids/define_boundary.o : phys_module.mod
grids/find_crossing.o : data_structure.mod
grids/find_R_surface.o : data_structure.mod
grids/find_RZ.o : data_structure.mod
grids/find_theta_surface.o : data_structure.mod
grids/find_Z_surface.o : data_structure.mod
grids/grid_bezier_square.o : parameters.mod
grids/grid_bezier_square.o : data_structure.mod
grids/grid_flux_surface.o : data_structure.mod
grids/grid_polar_bezier.o : parameters.mod
grids/grid_polar_bezier.o : data_structure.mod
grids/grid_polar_bezier_square.o : parameters.mod
grids/grid_polar_bezier_square.o : data_structure.mod
grids/grid_xpoint.o : data_structure.mod
matrix/ch_node_struct.o : parameters.mod
matrix/ch_node_struct.o : data_structure.mod
matrix/ch_nod_rhs_elm.o : parameters.mod
matrix/ch_nod_rhs_elm.o : data_structure.mod
matrix/construct_matrix.o : parameters.mod
matrix/construct_matrix.o : data_structure.mod
matrix/construct_matrix.o : global_distributed_matrix.mod
matrix/construct_matrix.o : phys_module.mod
matrix/construct_matrix.o : nodes_elements.mod
matrix/construct_matrix.o: timing/r3_info.h
matrix/construct_matrix_murge.o : data_structure.mod
matrix/construct_matrix_murge.o : global_distributed_matrix.mod
matrix/construct_matrix_murge.o : phys_module.mod
matrix/construct_matrix_murge.o : murge_module.mod
matrix/construct_matrix_murge.o : mumps_module.mod
matrix/construct_matrix_murge.o: timing/r3_info.h
matrix/global_matrix_structure.o : data_structure.mod
matrix/global_matrix_structure.o : global_distributed_matrix.mod
matrix/locate_irn_jcn.o : global_distributed_matrix.mod
communication/broadcast_boundary.o : data_structure.mod
communication/broadcast_elements.o : data_structure.mod
communication/broadcast_nodes.o : data_structure.mod
communication/broadcast_phys.o : phys_module.mod
communication/distribute_harmonics.o : parameters.mod
communication/distribute_harmonics.o : global_distributed_matrix.mod
communication/distribute_harmonics.o : mumps_module.mod
communication/distribute_nodes_elements.o : data_structure.mod
communication/distribute_vector.o : parameters.mod
communication/distribute_vector.o : global_distributed_matrix.mod
communication/distribute_vector.o : mumps_module.mod
communication/export_boundary.o : data_structure.mod
communication/export_grid.o : parameters.mod
communication/export_grid.o : data_structure.mod
communication/export_helena.o : data_structure.mod
communication/export_helena.o : phys_module.mod
communication/export_helena.o : data_structure.mod
communication/export_pov.o : parameters.mod
communication/export_pov.o : data_structure.mod
communication/export_pov.o : basis_at_gaussian.mod
communication/export_restart.o : data_structure.mod
communication/export_restart.o : phys_module.mod
communication/import_restart.o : data_structure.mod
communication/import_restart.o : phys_module.mod
communication/split_broadcast.o : mumps_module.mod
communication/update_deltas.o : data_structure.mod
communication/update_deltas.o : global_distributed_matrix.mod
communication/update_values.o : data_structure.mod
communication/vertex_is_local.o : murge_module.mod
datatypes/mod_data_structure.o : parameters.mod
data_structure.mod : datatypes/mod_data_structure.o
diagnostics/boundary_check.o : data_structure.mod
diagnostics/boundary_check.o : phys_module.mod
diagnostics/boundary_check.o : vacuum_response_module.mod
diagnostics/boundary_check.o : nodes_elements.mod
diagnostics/dlength.o : parameters.mod
diagnostics/energy.o : data_structure.mod
diagnostics/energy.o : gauss.mod
diagnostics/energy.o : basis_at_gaussian.mod
diagnostics/energy.o : phys_module.mod
diagnostics/find_axis.o : data_structure.mod
diagnostics/find_axis.o : gauss.mod
diagnostics/find_axis.o : basis_at_gaussian.mod
diagnostics/find_axis.o : data_structure.mod
diagnostics/find_flux_surfaces.o : data_structure.mod
diagnostics/find_xpoint.o : data_structure.mod
diagnostics/find_xpoint.o : gauss.mod
diagnostics/find_xpoint.o : basis_at_gaussian.mod
diagnostics/flux_surface_add_line.o : data_structure.mod
diagnostics/flux_surface_add_point.o : data_structure.mod
diagnostics/integrals_3D.o : data_structure.mod
diagnostics/integrals_3D.o : gauss.mod
diagnostics/integrals_3D.o : basis_at_gaussian.mod
diagnostics/integrals_3D.o : phys_module.mod
diagnostics/integrals.o : data_structure.mod
diagnostics/integrals.o : gauss.mod
diagnostics/integrals.o : basis_at_gaussian.mod
diagnostics/integrals.o : phys_module.mod
diagnostics/print_grid.o : data_structure.mod
diagnostics/psi_minmax.o : data_structure.mod
diagnostics/q_profile.o : data_structure.mod
diagnostics/q_profile.o : phys_module.mod
diagnostics/RZ_minmax.o : data_structure.mod
elements/initialise_basis.o : gauss.mod
elements/initialise_basis.o : basis_at_gaussian.mod
elements/initialise_basis.o : phys_module.mod
elements/interp.o : data_structure.mod
elements/interp_RZ.o : data_structure.mod
elements/mod_basis_at_gaussian.o : parameters.mod
elements/mod_basis_at_gaussian.o : gauss.mod
basis_at_gaussian.mod : elements/mod_basis_at_gaussian.o
gauss.mod : elements/mod_gauss.o
grids/define_boundary.o : phys_module.mod
grids/find_crossing.o : data_structure.mod
grids/find_R_surface.o : data_structure.mod
grids/find_RZ.o : data_structure.mod
grids/find_theta_surface.o : data_structure.mod
grids/find_Z_surface.o : data_structure.mod
grids/grid_bezier_square.o : parameters.mod
grids/grid_bezier_square.o : data_structure.mod
grids/grid_flux_surface.o : data_structure.mod
grids/grid_polar_bezier.o : parameters.mod
grids/grid_polar_bezier.o : data_structure.mod
grids/grid_polar_bezier_square.o : parameters.mod
grids/grid_polar_bezier_square.o : data_structure.mod
grids/grid_xpoint.o : data_structure.mod
jorek2_main.o : mumps_module.mod
jorek2_main.o : pastix_module.mod
jorek2_main.o : murge_module.mod
jorek2_main.o : data_structure.mod
jorek2_main.o : phys_module.mod
jorek2_main.o : global_distributed_matrix.mod
jorek2_main.o : nodes_elements.mod
jorek2_main.o : vacuum_response_module.mod
jorek2_main.o : data_structure.mod
jorek2_main.o: timing/r3_info.h
matrix/ch_node_struct.o : parameters.mod
matrix/ch_node_struct.o : data_structure.mod
matrix/ch_nod_rhs_elm.o : parameters.mod
matrix/ch_nod_rhs_elm.o : data_structure.mod
matrix/construct_matrix.o : parameters.mod
matrix/construct_matrix.o : data_structure.mod
matrix/construct_matrix.o : global_distributed_matrix.mod
matrix/construct_matrix.o : phys_module.mod
matrix/construct_matrix.o : nodes_elements.mod
matrix/construct_matrix.o: timing/r3_info.h
matrix/construct_matrix_murge.o : data_structure.mod
matrix/construct_matrix_murge.o : global_distributed_matrix.mod
matrix/construct_matrix_murge.o : phys_module.mod
matrix/construct_matrix_murge.o : murge_module.mod
matrix/construct_matrix_murge.o : mumps_module.mod
matrix/construct_matrix_murge.o: timing/r3_info.h
matrix/global_matrix_structure.o : data_structure.mod
matrix/global_matrix_structure.o : global_distributed_matrix.mod
matrix/locate_irn_jcn.o : global_distributed_matrix.mod
global_distributed_matrix.mod : matrix/mod_global_distributed_matrix.o
matrix/scale_global_matrix.o : global_distributed_matrix.mod
models/chgmt_node.o : parameters.mod
models/chgmt_node.o : data_structure.mod
models/current.o : phys_module.mod
models/density.o : phys_module.mod
models/element_matrix_GS.o : parameters.mod
models/element_matrix_GS.o : data_structure.mod
models/element_matrix_GS.o : gauss.mod
models/element_matrix_GS.o : basis_at_gaussian.mod
models/element_matrix_GS_inverse.o : parameters.mod
models/element_matrix_GS_inverse.o : data_structure.mod
models/element_matrix_GS_inverse.o : gauss.mod
models/element_matrix_GS_inverse.o : basis_at_gaussian.mod
models/element_matrix_poisson.o : parameters.mod
models/element_matrix_poisson.o : data_structure.mod
models/element_matrix_poisson.o : gauss.mod
models/element_matrix_poisson.o : basis_at_gaussian.mod
models/equilibrium.o : data_structure.mod
models/equilibrium.o : phys_module.mod
models/equilibrium.o : data_structure.mod
models/ffprime.o : phys_module.mod
models/model199/boundary_conditions.o : data_structure.mod
models/model199/boundary_conditions.o : global_distributed_matrix.mod
models/model199/boundary_conditions.o : phys_module.mod
models/model199/boundary_conditions_murge.o : data_structure.mod
models/model199/boundary_conditions_murge.o : global_distributed_matrix.mod
models/model199/boundary_conditions_murge.o : phys_module.mod
models/model199/boundary_conditions_murge.o : murge_module.mod
models/model199/boundary_matrix_open.o : parameters.mod
models/model199/boundary_matrix_open.o : data_structure.mod
models/model199/boundary_matrix_open.o : gauss.mod
models/model199/boundary_matrix_open.o : basis_at_gaussian.mod
models/model199/boundary_matrix_open.o : phys_module.mod
models/model199/element_matrix.o : parameters.mod
models/model199/element_matrix.o : data_structure.mod
models/model199/element_matrix.o : gauss.mod
models/model199/element_matrix.o : basis_at_gaussian.mod
models/model199/element_matrix.o : phys_module.mod
models/model199/element_matrix_fft.o : parameters.mod
models/model199/element_matrix_fft.o : parameters.mod
models/model199/element_matrix_fft.o : data_structure.mod
models/model199/element_matrix_fft.o : gauss.mod
models/model199/element_matrix_fft.o : basis_at_gaussian.mod
models/model199/element_matrix_fft.o : phys_module.mod
models/model199/element_matrix_fft.o : elm_fft.mod
elm_fft.mod : models/model199/element_matrix_fft.o
models/model199/initial_conditions.o : data_structure.mod
models/model199/initial_conditions.o : phys_module.mod
models/model199/initialise_parameters.o : phys_module.mod
parameters.mod : models/model199/mod_parameters.o
models/model199/sources.o : phys_module.mod
models/mod_nodes_elements.o : data_structure.mod
models/mod_nodes_elements.o : parameters.mod
nodes_elements.mod : models/mod_nodes_elements.o
models/mod_phys_module.o : parameters.mod
phys_module.mod : models/mod_phys_module.o
models/poisson.o : data_structure.mod
models/poisson.o : mumps_module.mod
models/poisson.o : pastix_module.mod
models/poisson.o : data_structure.mod
models/temperature_e.o : phys_module.mod
models/temperature.o : phys_module.mod
models/temperature_i.o : phys_module.mod
plots/plot_flux_surfaces.o : data_structure.mod
plots/plot_grid.o : parameters.mod
plots/plot_grid.o : data_structure.mod
plots/plot_profiles.o : data_structure.mod
plots/plot_profiles.o : phys_module.mod
plots/plot_profiles.o : basis_at_gaussian.mod
plots/plot_solution.o : parameters.mod
plots/plot_solution.o : data_structure.mod
plots/plot_solution.o : basis_at_gaussian.mod
plots/plot_solution.o : phys_module.mod
plots/plot_velocity_profile.o : data_structure.mod
plots/plot_velocity_profile.o : phys_module.mod
refinement/neighbours.o : data_structure.mod
refinement/Ref_Add_Elements.o : parameters.mod
refinement/Ref_Add_Elements.o : data_structure.mod
refinement/Ref_Add_Node.o : data_structure.mod
refinement/Ref_Add_Node.o : parameters.mod
refinement/Ref_boundary_node.o : parameters.mod
refinement/Ref_boundary_node.o : data_structure.mod
refinement/Ref_Check_Neighb_Stat.o : data_structure.mod
refinement/Ref_Find_Constrained_Node.o : parameters.mod
refinement/Ref_Find_Constrained_Node.o : data_structure.mod
refinement/Refine_Element.o : parameters.mod
refinement/Refine_Element.o : data_structure.mod
refinement/Refine_Elem_List.o : data_structure.mod
refinement/Refine_Elem_List.o : parameters.mod
refinement/Ref_Update_Index.o : parameters.mod
refinement/Ref_Update_Index.o : data_structure.mod
refinement/Ref_Update_Neighbours.o : data_structure.mod
solvers/gmres_driver.o : mumps_module.mod
solvers/gmres_driver.o : murge_module.mod
solvers/gmres_driver.o : global_distributed_matrix.mod
solvers/gmres_driver.o: timing/r3_info.h
solvers/gmres_matrix_vector.o : parameters.mod
solvers/gmres_matrix_vector.o : global_distributed_matrix.mod
solvers/gmres_matrix_vector.o : murge_module.mod
solvers/gmres_precondition.o : parameters.mod
solvers/gmres_precondition.o : mumps_module.mod
solvers/gmres_precondition.o : pastix_module.mod
solvers/gmres_precondition.o : murge_module.mod
solvers/gmres_precondition.o : global_distributed_matrix.mod
solvers/initialise_mumps.o : mumps_module.mod
solvers/initialise_pastix.o : pastix_module.mod
solvers/initialise_pastix.o : mumps_module.mod
solvers/mnewtax.o : data_structure.mod
solvers/mnewtax.o : data_structure.mod
mumps_module.mod : solvers/mod_mumps.o
murge_module.mod : solvers/mod_murge.o
pastix_module.mod : solvers/mod_pastix.o
solvers/solve_matrix_n.o : parameters.mod
solvers/solve_matrix_n.o : mumps_module.mod
solvers/solve_matrix_n.o : murge_module.mod
solvers/solve_matrix_n.o : pastix_module.mod
solvers/solve_matrix_n.o : global_distributed_matrix.mod
solvers/solve_matrix_n.o: timing/r3_info.h
solvers/solve_mumps_all.o : mumps_module.mod
solvers/solve_mumps_all.o : global_distributed_matrix.mod
solvers/solve_murge_all.o : parameters.mod
solvers/solve_murge_all.o : mumps_module.mod
solvers/solve_murge_all.o : pastix_module.mod
solvers/solve_murge_all.o : murge_module.mod
solvers/solve_murge_all.o : global_distributed_matrix.mod
solvers/solve_murge_all.o: timing/r3_info.h
solvers/solve_pastix_all.o : parameters.mod
solvers/solve_pastix_all.o : mumps_module.mod
solvers/solve_pastix_all.o : pastix_module.mod
solvers/solve_pastix_all.o : global_distributed_matrix.mod
solvers/update_rhs_n.o : parameters.mod
solvers/update_rhs_n.o : mumps_module.mod
solvers/update_rhs_n.o : global_distributed_matrix.mod
timing/r3_info.o: timing/r3_info.h
vacuum/ideal_wall.o : data_structure.mod
vacuum/ideal_wall.o : vacuum_response_module.mod
vacuum/ideal_wall.o : data_structure.mod
vacuum/ideal_wall.o : mumps_module.mod
vacuum/ideal_wall.o : pastix_module.mod
vacuum/ideal_wall.o : basis_at_gaussian.mod
vacuum/ideal_wall.o : gauss.mod
vacuum/ideal_wall.o : phys_module.mod
vacuum/ideal_wall.o : vacuum_response_module.mod
vacuum/ideal_wall.o : parameters.mod
vacuum/ideal_wall.o : data_structure.mod
vacuum/ideal_wall.o : gauss.mod
vacuum/ideal_wall.o : basis_at_gaussian.mod
vacuum/ideal_wall.o : data_structure.mod
vacuum/ideal_wall.o : data_structure.mod
vacuum/ideal_wall.o : vacuum_response_module.mod
vacuum/ideal_wall.o : phys_module.mod
vacuum_response_module.mod : vacuum/mod_vacuum_response.o
vacuum/vacuum.o : parameters.mod
vacuum/vacuum.o : data_structure.mod
vacuum/vacuum.o : gauss.mod
vacuum/vacuum.o : basis_at_gaussian.mod
vacuum/vacuum.o : phys_module.mod
vacuum/vacuum.o : global_distributed_matrix.mod
vacuum/vacuum.o : vacuum_response_module.mod
