#!/bin/sh
#PBS -N elm$num$name
#PBS -V
#PBS -j oe
#PBS -l walltime="47:59:00"
#PBS -l nodes=4:ppn=12
#PBS -o jorek.log
#PBS -e jorek.err

cd $PBS_O_WORKDIR

mpirun -n 4 -ppn 1 jorek_model303$name < in_jet_$type >> out_n0
