# Makefile for compiling fortran programs with automatic dependency
# generation and recognition of programs. Full support for parallel make.
#
# Object files are stored in $(OBJDIR)=.obj/
# Module files are stored in $(MODDIR)=.mod/
# Dependencies are stored in $(DEPDIR)=.dep/
#
# Known limitations:
# - Module/function/subroutine name must be equal to file name

# Include jorek-specific things and settings
include Makefile.inc
MODEL_NUMBER := $(subst model,,$(MODEL))

jorek_model$(MODEL_NUMBER): jorek2_main
	mv jorek2_main jorek_model$(MODEL_NUMBER)

# Some defaults and parsing logic for makefile.inc
include defaults.mk

.PHONY: .mod/version.h clean cleanall cleandep duplicates test particle_test doc docs
cleanall: clean cleandep
clean:
	@echo ">> Deleting Object Files <<"
	-@rm -r $(OBJDIR)
	@echo ">> Deleting Module Files <<"
	-@rm -r $(MODDIR)
	-@find . -name '*.mod' -delete -or -name '*.o' -delete
	-@rm -f particle_test_driver.f90
cleandep:
	@echo ">> Deleting Dependency Files <<"
	-@rm -r $(DEPDIR)
	-@find . -name '*.d' -delete 2>/dev/null
test: particle_test
particle_test:
	PYTHONPATH=$(FRUITPYDIR) python particles/tests/particle_test.py
doc docs: media/tests/all_pushers/penning.png media/tests/openadas/charge_state_time.png
	-@rm -r doc/ # workaround for FORD bug
	ford jorek.md --no-search



# Directories containing sources, ordered by number of files
DIRS := diagnostics			\
	models				\
	communication			\
	grids/grid_utils		\
	solvers				\
	models/$(MODEL)			\
	refinement			\
	matrix				\
	particles 			\
	particles/pushers 		\
	particles/examples 		\
	particles/diagnostics 		\
	particles/tests 		\
	particles/benchmarks/pusher     \
	elements			\
	grids				\
	plots				\
	diagnostics/new_diag		\
	diagnostics/postproc		\
	tools				\
	datatypes			\
	timing				\
	.				\
	vacuum
DIRS+=$(EXTRA_DIRS) # Specified in Makefile.inc or commandline

# All .f90 files we should generate .d dependency files for
depends:=$(basename $(notdir $(shell find $(DIRS) -maxdepth 1 -iname '*.f90')))
depends:=$(foreach dep,$(depends),$(DEPDIR)/$(dep).d)

# Check for multiple files with the same name in $(DIRS)
duplicates:
	@dups=`find $(DIRS) -maxdepth 1 -iname '*.f90' |\
	  xargs basename -s .f90 -a | sort | uniq -d`
	@if [[ -z "${dups// }" ]]; then echo "No duplicates detected"; \
	else echo "Duplicates found: ${dups}"; fi

printsettings:
	@echo "FC        = $(FC)"
	@echo "CC        = $(CC)"
	@echo "DEBUG     = $(DEBUG)"
	@echo "FLAGS     = $(FLAGS)"
	@echo "FFLAGS    = $(FFLAGS)"
	@echo "F90FLAGS  = $(F90FLAGS)"
	@echo "F77FLAGS  = $(F77FLAGS)"
	@echo "CFLAGS    = $(CFLAGS)"
	@echo "DEFINES   = $(DEFINES)"
	@echo "INCLUDES  = $(INCLUDES)"
	@echo "LIBS      = $(LIBS)"

# For each source dir add an explicit rule with the template
$(foreach dir,$(DIRS),$(eval $(call O_TEMPLATE,$(dir)/)))
# For each source dir add a rule to create dependency files
ifneq (cleanall,$(findstring cleanall,$(MAKECMDGOALS)))
  ifneq (cleandep,$(findstring cleandep,$(MAKECMDGOALS)))
    $(foreach dir,$(DIRS),$(eval $(call F90_D_TEMPLATE,$(dir)/)))
  endif
endif
# Include the dependency files that can be generated by the rules above
-include $(depends) # Make will build all of these and re-execute

# The included programs are defined in the $(depends) files
# For each of these programs add the default template
$(foreach prog,$(PROGRAM_SOURCES),$(eval $(call PROGRAM_TEMPLATE,$(prog))))
# To compile all programs found in $(DIRS)
all: $(basename $(notdir $(PROGRAM_SOURCES)))

# Special cases
# Add here: Global includes (as the line below)
INCLUDES += -Itiming # for r3_info.h
# C++ support
LIBS += -lstdc++
CXXFLAGS += -pedantic -Wall
# non-standard object files (extra include options, target-specific variable)
# Rule-specific includes: an example
particle_test_driver: INCLUDES += -I$(INC_FRUIT)
particle_test_driver: LIBS += -L$(LIB_FRUIT) -lfruit -Wl,-rpath=$(LIB_FRUIT)


# Benchmarks and other output used in the documentation
media/tests/all_pushers/penning.png: pusher_test # do not name other outputs
	./pusher_test
media/tests/openadas/charge_state_time.png: compare_mc_coronal # do not name other output
	./compare_mc_coronal
# Automatically download adas data for tungsten
particles/examples/%50_w.dat:
	wget http://open.adas.ac.uk/download/adf11/$*50/$*50_w.dat -O $@
compare_mc_coronal: | particles/examples/acd50_w.dat particles/examples/scd50_w.dat

eqdsk2jorek: LIBS+=-ldierckx

# Is this used by anyone? Otherwise we could remove it
# It is not updated to this format yet.
-include forcheck.mk
