# Makefile for compiling fortran programs with automatic dependency
# generation and recognition of programs. Full support for parallel make.
#
# Object files are stored in $(OBJDIR)=.obj/
# Module files are stored in $(MODDIR)=.mod/
# Dependencies are stored in $(DEPDIR)=.dep/
#
# Known limitations:
# - Module/function/subroutine name must be equal to file name

# Include jorek-specific things and settings
include Makefile.inc
MODEL_NUMBER := $(subst model,,$(MODEL))

jorek_model$(MODEL_NUMBER): jorek2_main
	cp jorek2_main jorek_model$(MODEL_NUMBER)

# Some defaults and parsing logic for makefile.inc
include defaults.mk

.PHONY: clean cleanall cleandep duplicates
cleanall: clean cleandep
clean:
	@echo ">> Deleting Object Files <<"
	-@rm -r $(OBJDIR)
	@echo ">> Deleting Module Files <<"
	-@rm -r $(MODDIR)
	-@find . -name '*.mod' -delete -or -name '*.o' -delete
cleandep:
	@echo ">> Deleting Dependency Files <<"
	-@rm -r $(DEPDIR)
	-@find . -name '*.d' -delete 2>/dev/null
test: particle_test nrt_unit
particle_test:
	+./util/fruit.sh particles/tests
nrt_unit:
	+./util/fruit.sh non_regression_tests/unit_tests
doc docs: media/tests/all_pushers/penning.png media/tests/openadas/charge_state_time.png
	-@rm -r doc/ # workaround for FORD bug
	ford jorek.md --no-search $(INCLUDES)



# Directories containing sources, ordered by number of files
DIRS := diagnostics			\
	models				\
	communication			\
	grids/grid_utils		\
	solvers				\
	models/$(MODEL)			\
	refinement			\
	matrix				\
	particles 			\
	particles/pushers 		\
	particles/examples 		\
	particles/diagnostics 		\
	particles/tests 		\
	particles/benchmarks/pusher_cartesian \
	particles/benchmarks/pusher	\
	particles/benchmarks/projection \
	elements			\
	grids				\
	plots				\
	diagnostics/new_diag		\
	diagnostics/postproc		\
	tools				\
	tools/fruit                     \
	non_regression_tests/unit_tests \
	tools/rng                       \
	datatypes			\
	benchmarks                      \
	.				\
	vacuum
DIRS+=$(EXTRA_DIRS) # Specified in Makefile.inc or commandline

# All .f90 files we should generate .d dependency files for
depends:=$(basename $(notdir $(shell find $(DIRS) -maxdepth 1 -iname '*.f90')))
depends:=$(foreach dep,$(depends),$(DEPDIR)/$(dep).d)

# Check for multiple files with the same name in $(DIRS)
duplicates:
	@dups=`find $(DIRS) -maxdepth 1 -iname '*.f90' |\
	  xargs basename -s .f90 -a | sort | uniq -d`
	@if [[ -z "${dups// }" ]]; then echo "No duplicates detected"; \
	else echo "Duplicates found: ${dups}"; fi

printsettings:
	@echo "FC        = $(FC)"
	@echo "CC        = $(CC)"
	@echo "DEBUG     = $(DEBUG)"
	@echo "FLAGS     = $(FLAGS)"
	@echo "FFLAGS    = $(FFLAGS)"
	@echo "F90FLAGS  = $(F90FLAGS)"
	@echo "F77FLAGS  = $(F77FLAGS)"
	@echo "CFLAGS    = $(CFLAGS)"
	@echo "DEFINES   = $(DEFINES)"
	@echo "INCLUDES  = $(INCLUDES)"
	@echo "LIBS      = $(LIBS)"

# For each source dir add an explicit rule with the template
$(foreach dir,$(DIRS),$(eval $(call O_TEMPLATE,$(dir)/)))
# For each source dir add a rule to create dependency files
ifneq (cleanall,$(findstring cleanall,$(MAKECMDGOALS)))
  ifneq (cleandep,$(findstring cleandep,$(MAKECMDGOALS)))
    $(foreach dir,$(DIRS),$(eval $(call F90_D_TEMPLATE,$(dir)/)))
  endif
endif
# Include the dependency files that can be generated by the rules above
-include $(depends) # Make will build all of these and re-execute

# The included programs are defined in the $(depends) files
# For each of these programs add the default template
$(foreach prog,$(PROGRAM_SOURCES),$(eval $(call PROGRAM_TEMPLATE,$(prog))))
# To compile all programs found in $(DIRS)
all: $(basename $(notdir $(PROGRAM_SOURCES)))
# A list of supported diagnostics, that should compile properly for regression
# testing to pass
most: jorek2_connection2 \
      jorek2_connection_stan \
      jorek2_diagno \
      jorek2_fieldlines_vtk \
      jorek2_four \
      jorek2_poincare \
      jorek2_powers \
      jorek2_target2vtk \
      jorek2vtk_3d \
      jorek2vtk \
      jorek2vtk_GaussVortTerms \
      jorek_to_helena \
      new_diag_demo \
      jorek2_postproc \
      rst_bin2hdf5 \
      rst_hdf52bin \
      jorek2_main
# Make all object files we know of
find_files = $(wildcard $(dir)/*.f90) $(wildcard $(dir)/*.c) $(wildcard $(dir)/*.f) $(wildcard $(dir)/*.cpp)
objs: $(foreach file,$(foreach dir,$(DIRS), $(find_files)), $(OBJDIR)/$(notdir $(basename $(file))).o)

# Special cases
# Add here: Global includes (as the line below)
INCLUDES += -Itools # for r3_info.h
# C++ support
LIBS += -lstdc++
CXXFLAGS += -pedantic -Wall


# Benchmarks and other output used in the documentation
media/tests/all_pushers/penning.png: pusher_test # do not name other outputs
	./pusher_test
media/tests/openadas/charge_state_time.png: compare_mc_coronal # do not name other output
	./compare_mc_coronal
# Automatically download adas data for tungsten
particles/examples/%50_w.dat:
	wget http://open.adas.ac.uk/download/adf11/$*50/$*50_w.dat -O $@
compare_mc_coronal: | particles/examples/acd50_w.dat particles/examples/scd50_w.dat

eqdsk2jorek: LIBS+=$(LIBDIERCKX)

# Is this used by anyone? Otherwise we could remove it
# It is not updated to this format yet.
-include forcheck.mk
