include ../config.in	

all : plot_flux_surfaces.o   \
      plot_grid.o            \
      plot_profiles.o        \
      plot_solution.o        \
      plot_velocity_profile.o 
      
modules :      

clean :
	rm *.o
