#!/bin/bash -l
#SBATCH -D ./
#SBATCH -J jorek_test
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=3
#SBATCH --cpus-per-task=13
#SBATCH --time=23:59:59
#SBATCH --mem=150000

module list |&tee modules

export OMP_NUM_THREADS=13
export OMP_PLACES=cores

#cp ./restart/jorek_restart.h5 .
#wait
srun ../jorek_model183 < intear_prerun  > logfile_TiTe_prerun
#wait
#cp jorek_restart.h5 ./restart/
#wait

scontrol show job $SLURM_JOB_ID
