#!/bin/bash -l
#SBATCH -D ./
#SBATCH -J jorek_test
#SBATCH --partition=general
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=5
#SBATCH --cpus-per-task=5
#SBATCH --time=23:59:00
#SBATCH --mem=300000

module list |&tee modules

export OMP_NUM_THREADS=5
export OMP_PLACES=cores

#cp ./restart/jorek_restart.h5 .
#wait
srun ../jorek_model183 < namelist_eccd2  > logfile_w7x_eccd1_new2.out
#wait
#cp jorek_restart.h5 ./restart/
#wait

scontrol show job $SLURM_JOB_ID
