include ../config.in

all:  modules \
      neighbours.o\
      Ref_Add_Elements.o\
      Ref_Add_Node.o\
      Ref_boundary_node.o\
      Ref_Check_Neighb_Stat.o\
      Ref_Find_Constrained_Node.o\
      Refine_Element.o\
      Refine_Elem_List.o\
      Ref_Update_Neighbours.o\
      Ref_Update_Index.o\
      #Ref_Active_Node.o\
      #Ref_Undo_Refine.o\
      #dealloc_Refine.o\
     
modules : mod_data_structure.o
 
clean :
	rm *.o *.mod
