#!/bin/bash
#SBATCH -J jorek
#SBATCH -N 1
#SBATCH -n 2
#SBATCH -t 00:01:00
#SBATCH -o ballooning_xpoint_303.%j.out
#SBATCH -e ballooning_xpoint_303.%j.err

##########################################################################
# Look to non-regression-tests/testcases/ballooning_xpoint_303/settings.sh
# to determine nb of nodes, MPI processes, and nb of threads
##########################################################################

ulimit -d unlimited
ulimit -s unlimited
ulimit -Sa
ulimit -Ha

CASE=ballooning_xpoint_303
startdir=`readlink -f $(dirname $PWD)`
findstr="non-regression-tests"
JOREK_HOME="${startdir%%${findstr}*}"

cd ${JOREK_HOME}
source ./non-regression-tests/job_scripts/helios/env.sh

#./run_test.sh -p $CASE
./non-regression-tests/run_test.sh -n $CASE
