#!/bin/bash
#SBATCH -J jorek
#SBATCH -N 1
#SBATCH -n 2
#SBATCH -t 00:01:00
#SBATCH -o h5_tearing_limiter_199.%j.out
#SBATCH -e h5_tearing_limiter_199.%j.err

###########################################################################
# Look to non-regression-tests/testcases/h5_tearing_limiter_199/settings.sh
# to determine nb of nodes, MPI processes, and nb of threads
###########################################################################

ulimit -d unlimited
ulimit -s unlimited
ulimit -Sa
ulimit -Ha
echo =0= $0

CASE=h5_tearing_limiter_199
startdir=`readlink -f $(dirname $PWD)`
findstr="non-regression-tests"
JOREK_HOME="${startdir%%${findstr}*}"

cd ${JOREK_HOME}
source ./non-regression-tests/job_scripts/helios/env.sh

#./run_test.sh -p $CASE
./non-regression-tests/run_test.sh -k -n $CASE
