#!/bin/bash
#SBATCH -J tearing_limiter_199
#SBATCH -N 1
#SBATCH -n 2
#SBATCH -t 00:50:00
#SBATCH -o %J.%j.out
#SBATCH -e %J.%j.err

########################################################################
# Look to non-regression-tests/testcases/tearing_limiter_199
# to determine nb of nodes, MPI processes, and nb of threads
########################################################################

ulimit -d unlimited
ulimit -s unlimited
ulimit -Sa
ulimit -Ha

CASE=tearing_limiter_199
JOREK_HOME=`readlink -f ${PWD}/../../..` # Assumption about source code location
echo " jorek_home = " ${JOREK_HOME}

cd ${JOREK_HOME}
source non-regression-tests/job_scripts/helios/env.sh
## Compile with:       
# non-regression-tests/run_test.sh -p $CASE
## Initial Long run: 
#non-regression-tests/run_test.sh -k -i -n $CASE 
## Restart run: 
non-regression-tests/run_test.sh -k -n $CASE 

