#!/bin/bash
#SBATCH -J jorek
#SBATCH -N 1
#SBATCH -n 2
#SBATCH -t 00:01:00
#SBATCH -o tearing_limiter_199.%j.out
#SBATCH -e tearing_limiter_199.%j.err

########################################################################
# Look to non-regression-tests/testcases/tearing_limiter_199/settings.sh
# to determine nb of nodes, MPI processes, and nb of threads
########################################################################

ulimit -d unlimited
ulimit -s unlimited
ulimit -Sa
ulimit -Ha

CASE=tearing_limiter_199
startdir=`readlink -f $(dirname $PWD)`
findstr="non-regression-tests"
JOREK_HOME="${startdir%%${findstr}*}"

#cd ${JOREK_HOME}/non-regression-tests
source job_scripts/helios/env.sh
cd ${JOREK_HOME}

#./run_test.sh -p $CASE
./non-regression-tests/run_test.sh -n $CASE

