#!/bin/bash
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --threads-per-core=1
#SBATCH -J Jorek
#SBATCH --time=4:00:00

ulimit -s unlimited
ulimit -Sa
ulimit -Ha

CASE=tearing_xpoint_302
JOREK_HOME=`readlink -f ${PWD}/../../..` # Assumption about source code location

cd ${JOREK_HOME}
source non_regression_tests/job_scripts/occigen/env.sh
## Compile with:       
# non_regression_tests/run_test.sh -p $CASE
## Initial Long run: 
#non_regression_tests/run_test.sh -k -i -n $CASE 
## Restart run: 
non_regression_tests/run_test.sh -k -n $CASE 
