DIR = timing
JOREK2_MAIN_SRC := $(JOREK2_MAIN_SRC)	\
	$(DIR)/r3_info.f90		\
	$(DIR)/r3_ctlk.c

JOREK2_POINCARE_SRC := $(JOREK2_POINCARE_SRC)

JOREK2_CONNECTION2_SRC := $(JOREK2_CONNECTION2_SRC)

JOREK2VTK_SRC := $(JOREK2VTK_SRC)

JOREK2FLVTK_SRC := $(JOREK2FLVTK_SRC)

JOREK2VTK3D_SRC := $(JOREK2VTK3D_SRC)

JOREK2_DIAGNO_SRC := $(JOREK2_DIAGNO_SRC)
