DIR = timing
JOREK2_MAIN_SRC := $(JOREK2_MAIN_SRC)	\
	$(DIR)/r3_info.f90		\
	$(DIR)/flushc.c			\
	$(DIR)/r3_ctlk.c                \
	$(DIR)/trace.f90

JOREK2_POINCARE_SRC := $(JOREK2_POINCARE_SRC) \
	$(DIR)/trace.f90

JOREK2_CONNECTION2_SRC := $(JOREK2_CONNECTION2_SRC) \
	$(DIR)/trace.f90

JOREK2VTK_SRC := $(JOREK2VTK_SRC) \
	$(DIR)/trace.f90

JOREK2FLVTK_SRC := $(JOREK2FLVTK_SRC) \
	$(DIR)/trace.f90

JOREK2VTK3D_SRC := $(JOREK2VTK3D_SRC) \
	$(DIR)/trace.f90

JOREK2_DIAGNO_SRC := $(JOREK2_DIAGNO_SRC) \
	$(DIR)/trace.f90

JOREK2FLVTK_SRC := $(JOREK2FLVTK_SRC) \
	$(DIR)/trace.f90
