DIR = tools

ALL_BINARIES_SRC := $(ALL_BINARIES_SRC)

JOREK2_MAIN_SRC := $(JOREK2_MAIN_SRC) 	\
	$(DIR)/fortran_pthread.c

RST_BIN2HDF5_SRC := $(RST_BIN2HDF5_SRC)  \
	$(DIR)/cla.f90

RST_HDF52BIN_SRC := $(RST_HDF52BIN_SRC)  \
	$(DIR)/cla.f90
