!> Routines to read in equilibrium generated by GVEC to JOREK import
module mod_import_gvec
implicit none
contains

subroutine import_gvec(node_list, element_list, file_name, ierr)
  use data_structure
  use phys_module

  type(type_node_list),    intent(inout)  :: node_list
  type(type_element_list), intent(inout)  :: element_list
  character*(*),           intent(in)     :: file_name       ! gvec import file name
  integer,                 intent(inout)  :: ierr            ! Error status
  call read_gvec_import(node_list, element_list, file_name, ierr)
end subroutine import_gvec

! Read data from GVEC import file into arrays of fourier harmonics for each degree of freedom
subroutine read_gvec_import(node_list, element_list, file_name, ierr)
  use tr_module
  use data_structure
  use phys_module
  
  type(type_node_list),    intent(inout)  :: node_list
  type(type_element_list), intent(inout)  :: element_list
  character*(*),           intent(in)     :: file_name       ! gvec import file name
  integer,                 intent(inout)  :: ierr            ! error status
  
  ! --- Local variables ---
  ! GVEC data
  integer          :: n_rad, n_theta, n_phi            ! Number of radial, poloidal and toroidal points
  integer          :: coord_type, num_periods, asym    ! GVEC coordinate type, number of field periods, equilibrium symmetry
  integer          :: m_max, n_max, n_modes            ! Maximum poloidal mode number, maximum toroidal mode number, number of modes
  integer          :: sin_range(2), cos_range(2)       ! Indices in fourier representation for sinusoidal and cosinusoidal modes
  real, allocatable        :: R_four(:, :, :), R_four_s(:, :, :), R_four_t(:, :, :), R_four_st(:, :, :) ! Arrays for node positions in fourier representation (i_theta, i_rad, i_four) 
  real, allocatable        :: Z_four(:, :, :), Z_four_s(:, :, :), Z_four_t(:, :, :), Z_four_st(:, :, :) ! Arrays for node Z positions in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: Psi_four(:, :, :), Psi_four_s(:, :, :), Psi_four_t(:, :, :), Psi_four_st(:, :, :) ! Arrays for node Poloidal flux in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: Psi_vac_four(:, :, :), Psi_vac_four_s(:, :, :), Psi_vac_four_t(:, :, :), Psi_vac_four_st(:, :, :) ! Arrays for node Poloidal flux contribution from the vacuum field in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: B_R_four(:, :, :), B_R_four_s(:, :, :), B_R_four_t(:, :, :), B_R_four_st(:, :, :) ! Arrays for node B_R in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: B_Z_four(:, :, :), B_Z_four_s(:, :, :), B_Z_four_t(:, :, :), B_Z_four_st(:, :, :) ! Arrays for node B_Z in fourier representation (i_theta, i_rad, i_four)

  ! JOREK grid
  integer          :: n_index_start, n_element_start, n_node_start

  ! General
  integer          :: idx, i_rad, i_theta, i_node, i_elm, itor, i_order, i_vertex                 ! Generic, radial, poloidal, node, element, toroidal harmonic, DOF order, and vertex indices
  integer          :: ivp, ivm, node_iv, node_ivp, node_ivm                              ! Adjacent nodes to current vertex for calculating element size
  real*8           :: delta_rm, delta_zm, delta_rp, delta_zp, dir_2, dir_3               ! Variables for element size and directions
  real*8           :: s_factor, theta_factor
 
  ! Smoothing variables at s=0
  real*8           :: R_average, Z_average
  real*8           :: BR_average, BZ_average

  integer          :: in_gvec=11                          ! Input stream from gvec
  integer          :: gvec_preamble_lines=63              ! Number of lines in gvec preamble
  integer          :: iostatus=0                          ! Error flag for reading vacuum field

  ! Read equilibrium parameters
  open(in_gvec, file=trim(file_name), status='old', iostat=ierr, form='formatted', access='sequential')
  if (ierr /= 0) then
    write(*, *) "Cannot open GVEC file..."
    stop
  end if
  do idx=1, gvec_preamble_lines
    read(in_gvec, *)
  enddo
  read(in_gvec, *) n_rad, n_theta, n_phi
  write(*, *)  "n_rad    n_theta    n_phi: ", n_rad, n_theta, n_phi
  !if ((n_theta .ne. n_tht) .or. (n_rad .ne. n_flux)) then
  !  write(*, *) "Number of radial and poloidal points does not match values in input file: ", n_rad, n_flux, n_theta, n_tht
  !  stop
  !endif
  read(in_gvec,*)
  read(in_gvec, *) coord_type, num_periods, asym, m_max, n_max, n_modes, sin_range(:), cos_range(:)
  write(*, *) "nfp    asym    m_max    n_max", num_periods, asym, m_max, n_max
  if (n_field_period .ne. num_periods) then
    write(*, *) "Number of field periods in GVEC equilibrium does not match input file: ", num_periods, n_field_period
    stop
  endif

  ! Check JOREK is compiled correctly from equilibrium
  if (n_tor .ne. n_modes) then
    write(*,*) "Number of modes in JOREK and GVEC do not match! (n_tor, n_modes):" , n_tor, n_modes
  endif

  ! Read fourier representation
  write(*, *) "Allocating data for grid"
  call tr_allocate(R_four, 1, n_theta, 1, n_rad, 1, n_modes,          "R_four", CAT_GRID)
  call tr_allocate(R_four_s, 1, n_theta, 1, n_rad, 1, n_modes,        "R_four_s", CAT_GRID)
  call tr_allocate(R_four_t, 1, n_theta, 1, n_rad, 1, n_modes,        "R_four_t", CAT_GRID)
  call tr_allocate(R_four_st, 1, n_theta, 1, n_rad, 1, n_modes,       "R_four_st", CAT_GRID)
  call tr_allocate(Z_four, 1, n_theta, 1, n_rad, 1, n_modes,          "Z_four", CAT_GRID)
  call tr_allocate(Z_four_s, 1, n_theta, 1, n_rad, 1, n_modes,        "Z_four_s", CAT_GRID)
  call tr_allocate(Z_four_t, 1, n_theta, 1, n_rad, 1, n_modes,        "Z_four_t", CAT_GRID)
  call tr_allocate(Z_four_st, 1, n_theta, 1, n_rad, 1, n_modes,       "Z_four_st", CAT_GRID)
  call tr_allocate(Psi_four, 1, n_theta, 1, n_rad, 1, n_modes,        "Psi_four", CAT_GRID)
  call tr_allocate(Psi_four_s, 1, n_theta, 1, n_rad, 1, n_modes,      "Psi_four_s", CAT_GRID)
  call tr_allocate(Psi_four_t, 1, n_theta, 1, n_rad, 1, n_modes,      "Psi_four_t", CAT_GRID)
  call tr_allocate(Psi_four_st, 1, n_theta, 1, n_rad, 1, n_modes,     "Psi_four_st", CAT_GRID)
  call tr_allocate(Psi_vac_four, 1, n_theta, 1, n_rad, 1, n_modes,    "Psi_vac_four", CAT_GRID)
  call tr_allocate(Psi_vac_four_s, 1, n_theta, 1, n_rad, 1, n_modes,  "Psi_vac_four_s", CAT_GRID)
  call tr_allocate(Psi_vac_four_t, 1, n_theta, 1, n_rad, 1, n_modes,  "Psi_vac_four_t", CAT_GRID)
  call tr_allocate(Psi_vac_four_st, 1, n_theta, 1, n_rad, 1, n_modes, "Psi_vac_four_st", CAT_GRID)
  call tr_allocate(B_R_four, 1, n_theta, 1, n_rad, 1, n_modes,    "B_R_vac_four", CAT_GRID)
  call tr_allocate(B_R_four_s, 1, n_theta, 1, n_rad, 1, n_modes,  "B_R_vac_four_s", CAT_GRID)
  call tr_allocate(B_R_four_t, 1, n_theta, 1, n_rad, 1, n_modes,  "B_R_vac_four_t", CAT_GRID)
  call tr_allocate(B_R_four_st, 1, n_theta, 1, n_rad, 1, n_modes, "B_R_vac_four_st", CAT_GRID)
  call tr_allocate(B_Z_four, 1, n_theta, 1, n_rad, 1, n_modes,    "B_Z_vac_four", CAT_GRID)
  call tr_allocate(B_Z_four_s, 1, n_theta, 1, n_rad, 1, n_modes,  "B_Z_vac_four_s", CAT_GRID)
  call tr_allocate(B_Z_four_t, 1, n_theta, 1, n_rad, 1, n_modes,  "B_Z_vac_four_t", CAT_GRID)
  call tr_allocate(B_Z_four_st, 1, n_theta, 1, n_rad, 1, n_modes, "B_Z_vac_four_st", CAT_GRID)
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') R_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') R_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') R_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') R_four_st
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Z_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Z_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Z_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Z_four_st
  
  ! Chi profile
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_four 
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_four_st
  Psi_vac_four = 0.0

  ! A_phi profile
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_four_st
!  read(in_gvec, '(A)', iostat=iostatus)
!  if (iostatus .eq. 0) then  ! Read vacuum field if it is present 
!    write(*, *) 'Vacuum field present'
!    read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_vac_four
!    read(in_gvec, '(A)')
!    read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_vac_four_s
!    read(in_gvec, '(A)')
!    read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_vac_four_t
!    read(in_gvec, '(A)')
!    read(in_gvec,'(*(6(e23.15,:,1X),/))') Psi_vac_four_st
!  else                  ! Assume the equilibrium is a vacuum field
!    write(*, *) 'Vacuum field not present'
!    iostatus = 0
!    Psi_vac_four    = Psi_four   
!    Psi_vac_four_s  = Psi_four_s 
!    Psi_vac_four_t  = Psi_four_t 
!    Psi_vac_four_st = Psi_four_st
!  endif
  ! B profiles
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_st
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_Z_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_Z_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_Z_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_Z_four_st

  close(in_gvec)

  ! Zero element and node variables
  n_element_start  = element_list%n_elements
  n_node_start     = node_list%n_nodes
  do idx=n_node_start+1,n_nodes_max
    node_list%node(idx)%x        = 0.d0
    node_list%node(idx)%values   = 0.d0
    node_list%node(idx)%index    = 0
    node_list%node(idx)%boundary = 0
  enddo
  do i_elm=n_element_start+1,n_elements_max
    element_list%element(i_elm)%vertex     = 0
    element_list%element(i_elm)%size       = 0.d0
    element_list%element(i_elm)%neighbours = 0
  enddo

  ! Set number of elements and nodes and check that the grid memory allocation is sufficient
  n_index_start = 0
  do idx=1,n_node_start
    n_index_start = max(n_index_start,maxval(node_list%node(idx)%index(:)))
  enddo
  element_list%n_elements  = n_element_start  + (n_rad-1)*n_theta
  node_list%n_nodes        = n_node_start     + n_rad*n_theta
  if (element_list%n_elements > n_elements_max) then
    write(*, *)  "ERROR: n_elements > n_elements_max - increase maximum number of elements: ", element_list%n_elements, n_elements_max
    stop
  endif
  if (node_list%n_nodes > n_nodes_max) then
    write(*, *)  "ERROR: n_nodes > n_nodes_max - increase maximum number of nodes: ", node_list%n_nodes, n_nodes_max
    stop
  endif

  ! Define elements based on nodes
  do i_rad=1,n_rad-1
   do i_theta=1,n_theta
      i_node  = n_theta*(i_rad-1) + i_theta
      i_elm = n_element_start + i_node
      element_list%element(i_elm)%vertex(1) = n_node_start + (i_rad-1)*n_theta + i_theta
      element_list%element(i_elm)%vertex(4) = n_node_start + (i_rad-1)*n_theta + i_theta + 1
      element_list%element(i_elm)%vertex(3) = n_node_start + i_rad*n_theta + i_theta + 1
      element_list%element(i_elm)%vertex(2) = n_node_start + i_rad*n_theta + i_theta
  
      ! Correct element nodes if index is last poloidal node
      if (i_theta .eq. n_theta) then
        element_list%element(i_elm)%vertex(4) = n_node_start + (i_rad-1)*n_theta + 1
        element_list%element(i_elm)%vertex(3) = n_node_start + i_rad*n_theta    + 1
      endif    
    enddo
  enddo
  
  ! Define node dofs
  s_factor = 1.0 / (n_rad - 1)
  theta_factor = 2 * PI / (n_theta)
  do i_rad=1,n_rad
    do i_theta=1,n_theta
      i_node = n_node_start + n_theta*(i_rad-1) + i_theta
      
      do idx=1, n_modes
        call get_gvec_mode_idx(idx, n_max, sin_range, cos_range, itor)

        ! Modify derivative dofs by conversion factor (1/3) for cubic hermite elements to bezier representation
        ! The additional s and theta factor are to compensate for element size being normalised ... ?
        node_list%node(i_node)%X(itor,1,1)        = R_four(i_theta, i_rad, idx)
        node_list%node(i_node)%X(itor,1,2)        = Z_four(i_theta, i_rad, idx)
        node_list%node(i_node)%X(itor,2,1)        = R_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%X(itor,2,2)        = Z_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%X(itor,3,1)        = R_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%X(itor,3,2)        = Z_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%X(itor,4,1)        = R_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
        node_list%node(i_node)%X(itor,4,2)        = Z_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0

        ! Read Psi
        node_list%node(i_node)%values(itor, 1, 1) = Psi_four(i_theta, i_rad, idx)
        node_list%node(i_node)%values(itor, 2, 1) = Psi_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%values(itor, 3, 1) = Psi_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%values(itor, 4, 1) = Psi_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
        node_list%node(i_node)%psi_vac(itor, 1)   = Psi_four(i_theta, i_rad, idx) - Psi_vac_four(i_theta, i_rad, idx)
        node_list%node(i_node)%psi_vac(itor, 2)   = (Psi_four_s(i_theta, i_rad, idx)  - Psi_vac_four_s(i_theta, i_rad, idx)) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%psi_vac(itor, 3)   = (Psi_four_t(i_theta, i_rad, idx)  - Psi_vac_four_t(i_theta, i_rad, idx)) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%psi_vac(itor, 4)   = (Psi_four_st(i_theta, i_rad, idx) - Psi_vac_four_st(i_theta, i_rad, idx)) * s_factor * theta_factor * 1.0 / 9.0
        
        ! Read B field R, Z components
        node_list%node(i_node)%b_field(itor, 1, 1) = B_R_four(i_theta, i_rad, idx)
        node_list%node(i_node)%b_field(itor, 2, 1) = B_R_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%b_field(itor, 3, 1) = B_R_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%b_field(itor, 4, 1) = B_R_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
        node_list%node(i_node)%b_field(itor, 1, 2) = B_Z_four(i_theta, i_rad, idx)
        node_list%node(i_node)%b_field(itor, 2, 2) = B_Z_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%b_field(itor, 3, 2) = B_Z_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%b_field(itor, 4, 2) = B_Z_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
      enddo
      
      ! Determine if node is on the boundary
      node_list%node(i_node)%boundary = 0
      if (i_rad .eq. n_rad) node_list%node(i_node)%boundary = 2
     
      ! Fix all axis nodes to have the same indices in global matrix structure is force_central_node = .t.
      if ((force_central_node) .and. (i_rad.eq.1)) then
        node_list%node(i_node)%index(1) = 1

        if (i_theta.eq.1) n_index_start = n_index_start + 1
        node_list%node(i_node)%index(2) = n_index_start + 1
        node_list%node(i_node)%index(3) = n_index_start + 2
        node_list%node(i_node)%index(4) = n_index_start + 3
        n_index_start = n_index_start + n_order
      else
        do i_order=1,n_order+1
          node_list%node(i_node)%index(i_order) = n_index_start + i_order
        enddo
        n_index_start = n_index_start + n_order+1
      endif

      node_list%node(i_node)%constrained=.false.
    enddo
  enddo

  ! fill in the size of the elements - in reality this is just the direction of the vertex in the element
  do i_elm=n_element_start+1 , element_list%n_elements   
    do i_vertex=1, 4                    ! over 4 corners of an element
  
      ivp = mod(i_vertex,4)   + 1         ! vertex with index one higher
      ivm = mod(i_vertex+2,4) + 1         ! vertex with index one below
  
      node_iv  = element_list%element(i_elm)%vertex(i_vertex)
      node_ivp = element_list%element(i_elm)%vertex(ivp)
      node_ivm = element_list%element(i_elm)%vertex(ivm)
  
      if ((i_vertex .eq. 1) .or. (i_vertex .eq.3)) then
        delta_Rp = node_list%node(node_ivp)%X(1,1,1) - node_list%node(node_iv)%X(1,1,1)
        delta_Zp = node_list%node(node_ivp)%X(1,1,2) - node_list%node(node_iv)%X(1,1,2)
        dir_2    = delta_Rp * node_list%node(node_iv)%X(1,2,1) + delta_Zp * node_list%node(node_iv)%X(1,2,2)
  
        delta_Rm = node_list%node(node_ivm)%X(1,1,1) - node_list%node(node_iv)%X(1,1,1)
        delta_Zm = node_list%node(node_ivm)%X(1,1,2) - node_list%node(node_iv)%X(1,1,2)
        dir_3    = delta_Rm * node_list%node(node_iv)%X(1,3,1) + delta_Zm * node_list%node(node_iv)%X(1,3,2)
      else
        delta_Rp = node_list%node(node_ivp)%X(1,1,1) - node_list%node(node_iv)%X(1,1,1)
        delta_Zp = node_list%node(node_ivp)%X(1,1,2) - node_list%node(node_iv)%X(1,1,2)
        dir_3    = delta_Rp * node_list%node(node_iv)%X(1,3,1) + delta_Zp * node_list%node(node_iv)%X(1,3,2)
  
        delta_Rm = node_list%node(node_ivm)%X(1,1,1) - node_list%node(node_iv)%X(1,1,1)
        delta_Zm = node_list%node(node_ivm)%X(1,1,2) - node_list%node(node_iv)%X(1,1,2)
        dir_2    = delta_Rm * node_list%node(node_iv)%X(1,2,1) + delta_Zm * node_list%node(node_iv)%X(1,2,2)
      endif
  
      if (dir_2 .ne. 0.d0) then
        dir_2 = dir_2 / abs(dir_2)
      else
        dir_2 = 1.d0
      endif
      if (dir_3 .ne. 0.d0) then
        dir_3 = dir_3 / abs(dir_3)
      else
        dir_3 = -1.d0
        if (i_vertex.eq.1) dir_3 = 1.d0              ! admittedly not very elegant
      endif
  
      element_list%element(i_elm)%size(i_vertex,1) = 1.d0
      element_list%element(i_elm)%size(i_vertex,2) = dir_2
      element_list%element(i_elm)%size(i_vertex,3) = dir_3
      element_list%element(i_elm)%size(i_vertex,4) = element_list%element(i_elm)%size(i_vertex,2) * element_list%element(i_elm)%size(i_vertex,3)
    enddo
  enddo

  ! Smooth axis points - GVEC axis points are shifted from s=0 for numerical stability. The points need to be averaged onto s=0
  do idx=1, n_tor
    R_average=0.0; Z_average=0.0; BR_average=0.0; BZ_average=0.0
    do i_node=1, n_tht
      R_average     = R_average   + node_list%node(i_node)%x(idx, 1, 1)
      Z_average     = Z_average   + node_list%node(i_node)%x(idx, 1, 2)
      BR_average    = BR_average  + node_list%node(i_node)%b_field(idx, 1, 1)
      BZ_average    = BZ_average  + node_list%node(i_node)%b_field(idx, 1, 2)
    enddo
    do i_node=1, n_tht
      node_list%node(i_node)%x(idx, 1, 1) = R_average   / n_tht
      node_list%node(i_node)%x(idx, 3, 1) = 0.0
      node_list%node(i_node)%x(idx, 4, 1) = 0.0
      node_list%node(i_node)%x(idx, 1, 2) = Z_average   / n_tht
      node_list%node(i_node)%x(idx, 3, 2) = 0.0
      node_list%node(i_node)%x(idx, 4, 2) = 0.0
      !node_list%node(i_node)%b_field(idx, 1, 1) = BR_average  / n_tht
      node_list%node(i_node)%b_field(idx, 3, 1) = 0.0
      node_list%node(i_node)%b_field(idx, 4, 1) = 0.0
      !node_list%node(i_node)%b_field(idx, 1, 1) = BZ_average  / n_tht
      node_list%node(i_node)%b_field(idx, 3, 2) = 0.0
      node_list%node(i_node)%b_field(idx, 4, 2) = 0.0
    enddo
  enddo

  ! De-allocate DOFs
  call tr_deallocate(R_four,          "R_four", CAT_GRID)
  call tr_deallocate(R_four_s,        "R_four_s", CAT_GRID)
  call tr_deallocate(R_four_t,        "R_four_t", CAT_GRID)
  call tr_deallocate(R_four_st,       "R_four_st", CAT_GRID)
  call tr_deallocate(Z_four,          "Z_four", CAT_GRID)
  call tr_deallocate(Z_four_s,        "Z_four_s", CAT_GRID)
  call tr_deallocate(Z_four_t,        "Z_four_t", CAT_GRID)
  call tr_deallocate(Z_four_st,       "Z_four_st", CAT_GRID)
  call tr_deallocate(Psi_four,        "Psi_four", CAT_GRID)
  call tr_deallocate(Psi_four_s,      "Psi_four_s", CAT_GRID)
  call tr_deallocate(Psi_four_t,      "Psi_four_t", CAT_GRID)
  call tr_deallocate(Psi_four_st,     "Psi_four_st", CAT_GRID)
  call tr_deallocate(Psi_vac_four,    "Psi_vac_four", CAT_GRID)
  call tr_deallocate(Psi_vac_four_s,  "Psi_vac_four_s", CAT_GRID)
  call tr_deallocate(Psi_vac_four_t,  "Psi_vac_four_t", CAT_GRID)
  call tr_deallocate(Psi_vac_four_st, "Psi_vac_four_st", CAT_GRID)
  call tr_deallocate(B_R_four,        "B_R_four", CAT_GRID)
  call tr_deallocate(B_R_four_s,      "B_R_four_s", CAT_GRID)
  call tr_deallocate(B_R_four_t,      "B_R_four_t", CAT_GRID)
  call tr_deallocate(B_R_four_st,     "B_R_four_st", CAT_GRID)
  call tr_deallocate(B_Z_four,        "B_Z_four", CAT_GRID)
  call tr_deallocate(B_Z_four_s,      "B_Z_four_s", CAT_GRID)
  call tr_deallocate(B_Z_four_t,      "B_Z_four_t", CAT_GRID)
  call tr_deallocate(B_Z_four_st,     "B_Z_four_st", CAT_GRID)
end subroutine read_gvec_import

subroutine get_gvec_mode_idx(idx, n_max, sin_range, cos_range, itor)
  integer, intent(in)     :: idx, n_max, sin_range(2), cos_range(2)
  integer, intent(inout)  :: itor
  
  if (idx .gt. n_max) then
    ! cosine
    if (idx .eq. n_max + 1) then
      ! axisymmetric n=0
      itor = 1
    else
      itor = 2 * (idx - n_max - 1)  
    endif
  else
    ! sine
    itor = 2 * idx + 1
  endif 
end subroutine get_gvec_mode_idx

end module mod_import_gvec
