#!/bin/bash
#SBATCH -J tearing_xpoint_303
#SBATCH -N 2
#SBATCH -n 2
#SBATCH -t 00:50:00
#SBATCH -o tearing_xpoint.303.%j.out
#SBATCH -e tearing_xpoint.303.%j.err

########################################################################
# Look to non_regression_tests/testcases/tearing_xpoint_303/settings.sh
# to determine nb of nodes, MPI processes, and nb of threads
########################################################################

ulimit -d unlimited
ulimit -s unlimited
ulimit -Sa
ulimit -Ha

CASE=tearing_xpoint_303
JOREK_HOME=`readlink -f ${PWD}/../../..` # Assumption about source code location

cd ${JOREK_HOME}
source non_regression_tests/job_scripts/helios/env.sh
## Compile with:       
# non_regression_tests/run_test.sh -p $CASE
## Initial Long run: 
#non_regression_tests/run_test.sh -k -i -n $CASE 
## Restart run: 
non_regression_tests/run_test.sh -k -n $CASE 

